import axios, {
    AxiosResponse,
    AxiosError
} from "./node_modules/axios/index";

interface IMusicRecord {
    id: number;
    title: string;
    artist: string;
    duration: number;
    yearOfPublication: number;
}

let baseUri: string = "http://matlar.azurewebsites.net/api/MusicRecords";

let buttonElement: HTMLButtonElement = <HTMLButtonElement>document.getElementById("getAllButton");
buttonElement.addEventListener("click", showAllCars);

let outputElement: HTMLDivElement = <HTMLDivElement>document.getElementById("content");

let buttonDeleteElement: HTMLButtonElement = <HTMLButtonElement>document.getElementById("deleteButton");
buttonDeleteElement.addEventListener("click", deleteCar);

let addButton: HTMLButtonElement = <HTMLButtonElement>document.getElementById("addButton");
addButton.addEventListener("click", addCar);

let recordList: IMusicRecord;



function showAllCars(): void {
    axios.get<IMusicRecord[]>(baseUri)
        .then(function (response: AxiosResponse<IMusicRecord[]>): void {
            // element.innerHTML = generateSuccessHTMLOutput(response);
            // outputHtmlElement.innerHTML = generateHtmlTable(response.data);
            // outputHtmlElement.innerHTML = JSON.stringify(response.data);
            let result: string = "<ul>";
            response.data.forEach((record: IMusicRecord) => {
                result += "<li>" + record.id + " " + record.artist + " " + record.title + "</li>";
            });
            result += "</ul>";
            outputElement.innerHTML = result;
        })
        .catch(function (error: AxiosError): void { // error in GET or in generateSuccess?
            if (error.response) {
                // the request was made and the server responded with a status code
                // that falls out of the range of 2xx
                // https://kapeli.com/cheat_sheets/Axios.docset/Contents/Resources/Documents/index
                outputElement.innerHTML = error.message;
            } else { // something went wrong in the .then block?
                outputElement.innerHTML = error.message;
            }
        });
}

function deleteCar(): void {
    let output: HTMLDivElement = <HTMLDivElement>document.getElementById("contentDelete");
    let inputElement: HTMLInputElement = <HTMLInputElement>document.getElementById("deleteInput");
    let id: string = inputElement.value;
    let uri: string = baseUri + "/" + id;
    axios.delete<IMusicRecord>(uri)
        .then(function (response: AxiosResponse<IMusicRecord>): void {
            // element.innerHTML = generateSuccessHTMLOutput(response);
            // outputHtmlElement.innerHTML = generateHtmlTable(response.data);
            console.log(JSON.stringify(response));
            output.innerHTML = response.status + " ";
        })
        .catch(function (error: AxiosError): void { // error in GET or in generateSuccess?
            if (error.response) {
                // the request was made and the server responded with a status code
                // that falls out of the range of 2xx
                // https://kapeli.com/cheat_sheets/Axios.docset/Contents/Resources/Documents/index
                output.innerHTML = error.message;
            } else { // something went wrong in the .then block?
                output.innerHTML = error.message;
            }
        });
}

function addCar(): void {
    let addTitleElement: HTMLInputElement = <HTMLInputElement>document.getElementById("addtitle");
    let addArtistElement: HTMLInputElement = <HTMLInputElement>document.getElementById("addartist");
    let addDurationElement: HTMLInputElement = <HTMLInputElement>document.getElementById("addduration");
    let addYOPElement: HTMLInputElement = <HTMLInputElement>document.getElementById("addyop");
    let addIDElement: HTMLInputElement = <HTMLInputElement>document.getElementById("addid");
    let myArtist: string = addArtistElement.value;
    let myAlbum: string = addTitleElement.value;
    let myDuration: number = Number(addDurationElement.value);
    let myYOP: number = Number(addYOPElement.value);
    let myID: number = Number(addIDElement.value);
    let output: HTMLDivElement = <HTMLDivElement>document.getElementById("contentAdd");
    // id is generated by the back-end (REST service)
    axios.post<IMusicRecord>(baseUri, { artist: myArtist, title: myAlbum, price: myDuration, yearOfPublication: myYOP, id: myID })
        .then((response: AxiosResponse) => {
            let message: string = "response " + response.status + " " + response.statusTexts;
            output.innerHTML = message;
            console.log(message);
        })
        .catch((error: AxiosError) => {
            output.innerHTML = error.message;
            console.log(error);
        });
}